FROM node:18-alpine AS build

WORKDIR /app

COPY package.json yarn.lock config-overrides.js ./
RUN yarn config set registry https://registry.npmjs.org && \
  yarn install --network-timeout 600000

COPY . ./

ARG REACT_APP_API_URL=/api
ENV REACT_APP_API_URL=${REACT_APP_API_URL}
ENV NODE_OPTIONS=--openssl-legacy-provider

RUN yarn build

FROM nginx:1.27-alpine

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
