export const queryKeys = {
  auth: ["auth"],
  users: ["users"],
  user: (id: string | number) => ["users", id],
  sizes: ["sizes"],
  size: (id: string | number) => ["sizes", id],
  products: ["products"],
  product: (id: string | number) => ["products", id],
  productPrices: (productId: string | number) => ["products", productId, "prices"],
  productPrice: (productId: string | number, id: string | number) => ["products", productId, "prices", id],
  productImages: (productId: string | number) => ["products", productId, "images"],
  coupons: ["coupons"],
  coupon: (id: string | number) => ["coupons", id],
  stockOperations: ["stock-operations"],
  stockOperation: (id: string | number) => ["stock-operations", id],
  dashboard: ["dashboard"],
  charts: ["charts"],
  reports: ["reports"],
  profile: ["profile"],
};
